[package]
name = 'fcl'
version = '0.1.4'
edition = '2021'
rust-version = "1.65.0"

[lib]
crate-type = ['staticlib']

[dependencies]
extendr-api = "0.8.0"
chrono = "0.4.40"

[dev-dependencies]
extendr-engine = "0.8.0"
