# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_fcl_wrappers", use_symbols = TRUE, package_name = "fcl")

#' @docType package
#' @usage NULL
#' @useDynLib fcl, .registration = TRUE
NULL

rust_bond_result <- function(value_date, mty_date, redem_value, cpn_rate, cpn_freq, ref_date, clean_price) .Call(wrap__rust_bond_result, value_date, mty_date, redem_value, cpn_rate, cpn_freq, ref_date, clean_price)

rust_bond_cf <- function(value_date, mty_date, redem_value, cpn_rate, cpn_freq, ref_date) .Call(wrap__rust_bond_cf, value_date, mty_date, redem_value, cpn_rate, cpn_freq, ref_date)

RRtn <- new.env(parent = emptyenv())

RRtn$new <- function(ids, dates, mvs, pls) .Call(wrap__RRtn__new, ids, dates, mvs, pls)

RRtn$twrr_cr <- function(id, from, to) .Call(wrap__RRtn__twrr_cr, self, id, from, to)

RRtn$twrr_dr <- function(id, from, to) .Call(wrap__RRtn__twrr_dr, self, id, from, to)

RRtn$cum_pl <- function(id, from, to) .Call(wrap__RRtn__cum_pl, self, id, from, to)

RRtn$dietz_avc <- function(id, from, to) .Call(wrap__RRtn__dietz_avc, self, id, from, to)

RRtn$dietz <- function(id, from, to) .Call(wrap__RRtn__dietz, self, id, from, to)

RRtn$dates <- function(from, to) .Call(wrap__RRtn__dates, from, to)

#' @export
`$.RRtn` <- function (self, name) { func <- RRtn[[name]]; environment(func) <- environment(); func }

