# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_fcl_wrappers", use_symbols = TRUE, package_name = "fcl")

#' @docType package
#' @usage NULL
#' @useDynLib fcl, .registration = TRUE
NULL

#' Calculate the Bond's YTM, Maclay Duration, Modified Duration
#' @param value_date,mty_date the value and maturity date of the bond
#' @param redem_value,cpn_rate,cpn_freq the redemption value, coupon rate and coupon frequency of the bond.
#'   Note that the **frequency** can only be one of 1, 2, 4, 0 (pay at mature)
#' @param ref_date,clean_price the reference date and the clean price that used to calculate the bond results
#' @return a double vector with 3 elements: ytm, macd and modd
#' @export
bond_result <- function(value_date, mty_date, redem_value, cpn_rate, cpn_freq, ref_date, clean_price) .Call(wrap__bond_result, value_date, mty_date, redem_value, cpn_rate, cpn_freq, ref_date, clean_price)

#' Generate bond's cash flows
#' @inheritParams bond_result
#' @export
bond_cf <- function(value_date, mty_date, redem_value, cpn_rate, cpn_freq, ref_date) .Call(wrap__bond_cf, value_date, mty_date, redem_value, cpn_rate, cpn_freq, ref_date)

RRtn <- new.env(parent = emptyenv())

RRtn$new <- function(ids, dates, mvs, pls) .Call(wrap__RRtn__new, ids, dates, mvs, pls)

RRtn$twrr <- function(id, from, to) .Call(wrap__RRtn__twrr, self, id, from, to)

RRtn$dietz_avc <- function(id, from, to) .Call(wrap__RRtn__dietz_avc, self, id, from, to)

RRtn$dietz <- function(id, from, to) .Call(wrap__RRtn__dietz, self, id, from, to)

RRtn$dates <- function(from, to) .Call(wrap__RRtn__dates, from, to)

#' @export
`$.RRtn` <- function (self, name) { func <- RRtn[[name]]; environment(func) <- environment(); func }

